# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/shiv/Research/temp-del/ProgrammingEnclaves

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/shiv/Research/temp-del/ProgrammingEnclaves

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shiv/Research/temp-del/ProgrammingEnclaves/CMakeFiles /home/shiv/Research/temp-del/ProgrammingEnclaves/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shiv/Research/temp-del/ProgrammingEnclaves/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Prt_trusted_static

# Build rule for target.
Prt_trusted_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Prt_trusted_static
.PHONY : Prt_trusted_static

# fast build rule for target.
Prt_trusted_static/fast:
	$(MAKE) -f Submodule/P/Src/Prt/CMakeFiles/Prt_trusted_static.dir/build.make Submodule/P/Src/Prt/CMakeFiles/Prt_trusted_static.dir/build
.PHONY : Prt_trusted_static/fast

#=============================================================================
# Target rules for targets named libhandler

# Build rule for target.
libhandler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libhandler
.PHONY : libhandler

# fast build rule for target.
libhandler/fast:
	$(MAKE) -f Submodule/P/Src/Prt/CMakeFiles/libhandler.dir/build.make Submodule/P/Src/Prt/CMakeFiles/libhandler.dir/build
.PHONY : libhandler/fast

#=============================================================================
# Target rules for targets named Prt

# Build rule for target.
Prt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Prt
.PHONY : Prt

# fast build rule for target.
Prt/fast:
	$(MAKE) -f Submodule/P/Src/Prt/CMakeFiles/Prt.dir/build.make Submodule/P/Src/Prt/CMakeFiles/Prt.dir/build
.PHONY : Prt/fast

#=============================================================================
# Target rules for targets named dep_enclave

# Build rule for target.
dep_enclave: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dep_enclave
.PHONY : dep_enclave

# fast build rule for target.
dep_enclave/fast:
	$(MAKE) -f Samples/PingEnclavePongOutside/Src/enclave/CMakeFiles/dep_enclave.dir/build.make Samples/PingEnclavePongOutside/Src/enclave/CMakeFiles/dep_enclave.dir/build
.PHONY : dep_enclave/fast

#=============================================================================
# Target rules for targets named enclave

# Build rule for target.
enclave: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 enclave
.PHONY : enclave

# fast build rule for target.
enclave/fast:
	$(MAKE) -f Samples/PingEnclavePongOutside/Src/enclave/CMakeFiles/enclave.dir/build.make Samples/PingEnclavePongOutside/Src/enclave/CMakeFiles/enclave.dir/build
.PHONY : enclave/fast

#=============================================================================
# Target rules for targets named dep_

# Build rule for target.
dep_: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dep_
.PHONY : dep_

# fast build rule for target.
dep_/fast:
	$(MAKE) -f Samples/PingEnclavePongOutside/Src/app/CMakeFiles/dep_.dir/build.make Samples/PingEnclavePongOutside/Src/app/CMakeFiles/dep_.dir/build
.PHONY : dep_/fast

#=============================================================================
# Target rules for targets named app

# Build rule for target.
app: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 app
.PHONY : app

# fast build rule for target.
app/fast:
	$(MAKE) -f Samples/PingEnclavePongOutside/Src/app/CMakeFiles/app.dir/build.make Samples/PingEnclavePongOutside/Src/app/CMakeFiles/app.dir/build
.PHONY : app/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Prt_trusted_static"
	@echo "... libhandler"
	@echo "... Prt"
	@echo "... dep_enclave"
	@echo "... enclave"
	@echo "... dep_"
	@echo "... app"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

