/*
 * Copyright (C) 2011-2019 Intel Corporation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in
 *     the documentation and/or other materials provided with the
 *     distribution.
 *   * Neither the name of Intel Corporation nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */


//This file contains samples of messages sent between the sample ISV application
//and the sample service provider. It is intended to be used so that authors
//of other service providers can verify that the messages generated by their
//remote attestation service matches.

#include <stdint.h>

#define MSG1_BODY_SIZE 68

extern uint8_t msg1_sample1[MSG1_BODY_SIZE];

extern uint8_t msg1_sample2[MSG1_BODY_SIZE];

#define MSG2_BODY_SIZE 176

extern uint8_t msg2_sample1[MSG2_BODY_SIZE];

extern uint8_t msg2_sample2[MSG2_BODY_SIZE];

#define MSG3_BODY_SIZE 1452

extern uint8_t msg3_sample1[MSG3_BODY_SIZE];

extern uint8_t msg3_sample2[MSG3_BODY_SIZE];

#define ATTESTATION_MSG_BODY_SIZE 145

extern uint8_t attestation_msg_sample1[ATTESTATION_MSG_BODY_SIZE]; 

extern uint8_t attestation_msg_sample2[ATTESTATION_MSG_BODY_SIZE];

extern uint8_t* msg1_samples[2];